export interface MapperPresetOption {
  description: string;
  id: string;
  label: string;
}

export const mapperPresetOptions: MapperPresetOption[] = [
  {
    description: 'ID, label, data, endpoint, selector, layer, and graph mapping examples.',
    id: 'comprehensive-starter',
    label: 'Comprehensive starter'
  }
];

function sourceIdLiteral(sourceId: string) {
  return sourceId.replace(/"/g, '\\"');
}

export function mapperPresetDocument(presetId: string, sourceId: string) {
  if (presetId !== 'comprehensive-starter') return undefined;
  return [
    'version: 1',
    'identity:',
    `  sourceId: "${sourceIdLiteral(sourceId)}"`,
    '  sourceIdLabel: source_id',
    'rules:',
    '  - id: node-health-by-id',
    '    metric: topoviewer_node_health',
    '    select: node',
    '    join: node_id',
    '    value: health',
    '    states:',
    '      warning: ">=70"',
    '      error: ">=90"',
    '    style:',
    '      default:',
    '        statusColor: "#4caf50"',
    '        badgeLabel: OK',
    '      warning:',
    '        statusColor: "#ff9800"',
    '        outlineColor: "#ff9800"',
    '        outlineWidth: 4',
    '        badgeLabel: WARN',
    '      error:',
    '        statusColor: "#d32f2f"',
    '        outlineColor: "#d32f2f"',
    '        outlineWidth: 6',
    '        badgeLabel: DOWN',
    '  - id: link-state-by-id',
    '    metric: topoviewer_link_up',
    '    select: link',
    '    join: link_id',
    '    value: up',
    '    states:',
    '      down: "==0"',
    '    style:',
    '      default:',
    '        label: UP',
    '        lineColor: "#4caf50"',
    '        lineWidth: 3',
    '      down:',
    '        label: DOWN',
    '        lineColor: "#d32f2f"',
    '        lineStyle: dashed',
    '        lineWidth: 7',
    'mappings:',
    '  - id: path-slo-by-id',
    '    metric: topoviewer_path_latency_ms',
    '    target:',
    '      kind: path',
    '      resolve:',
    '        by: id',
    '        metricLabel: path_id',
    '    value:',
    '      as: latencyMs',
    '    thresholds:',
    '      warning: 80',
    '      error: 150',
    '    overlay:',
    '      lineColorBySeverity: true',
    '      lineWidthBySeverity: true',
    '      label: "{{ value | round }} ms"',
    '  - id: node-role-label-match',
    '    metric: topoviewer_role_health',
    '    target:',
    '      kind: node',
    '      resolve:',
    '        by: label',
    '        key: role',
    '        metricLabel: role',
    '    overlay:',
    '      statusMarker: true',
    '      badgeLabel: "{{ severity }}"',
    '  - id: link-circuit-data-match',
    '    metric: topoviewer_circuit_utilization',
    '    target:',
    '      kind: link',
    '      resolve:',
    '        by: data',
    '        key: circuitId',
    '        metricLabel: circuit_id',
    '    value:',
    '      as: utilizationPercent',
    '    thresholds:',
    '      warning: 70',
    '      error: 90',
    '    overlay:',
    '      lineColorBySeverity: true',
    '      label: "{{ value | round }}%"',
    '  - id: link-endpoint-match',
    '    metric: topoviewer_endpoint_utilization',
    '    target:',
    '      kind: link',
    '      resolve:',
    '        by: endpoint',
    '        sourceLabel: source',
    '        targetLabel: target',
    '    overlay:',
    '      lineWidthBySeverity: true',
    '      label: "{{ source }} to {{ target }}"',
    '  - id: selector-pe-health',
    '    metric: topoviewer_pe_health',
    '    target:',
    '      kind: node',
    '      resolve:',
    '        by: selector',
    '        selector: node[labels.role = "pe"]',
    '    overlay:',
    '      statusMarker: true',
    '      badgeLabel: PE',
    '  - id: layer-aggregate-health',
    '    metric: topoviewer_layer_health',
    '    target:',
    '      kind: layer',
    '      resolve:',
    '        by: aggregate',
    '    overlay:',
    '      label: "{{ severity }} layer"',
    '      propagateToLayerMembers: true',
    '  - id: graph-summary-incidents',
    '    metric: topoviewer_graph_incidents',
    '    target:',
    '      kind: graph',
    '      resolve:',
    '        by: aggregate',
    '    overlay:',
    '      label: "{{ value | round }} incident(s)"',
    ''
  ].join('\n');
}
