username: admin
password: NokiaSrl1!
skip-verify: true
encoding: json_ietf
timeout: 10s

targets:
  spine1:
    address: spine1:57400
  spine2:
    address: spine2:57400
  leaf1:
    address: leaf1:57400
  leaf2:
    address: leaf2:57400

subscriptions:
  interface-state:
    mode: stream
    stream-mode: sample
    sample-interval: 10s
    paths:
      - /interface[name=*]/oper-state
      - /interface[name=*]/statistics/in-octets
      - /interface[name=*]/statistics/out-octets
      - /interface[name=*]/statistics/in-error-packets
      - /interface[name=*]/statistics/out-error-packets
  system-health:
    mode: stream
    stream-mode: sample
    sample-interval: 15s
    paths:
      - /platform/control/slot[id=*]/oper-state
      - /system/information/version

outputs:
  prometheus:
    type: prometheus
    listen: :9804
    path: /metrics

processors:
  add-source-label:
    event-add-tag:
      value-names:
        - ".*"
      tags:
        topology: clab-clos
