#!/usr/bin/env node

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';

const GENERATED_DOC_PATHS = [
  'README.md',
  'docs/index.md',
  'docs/topoviewer'
];

const MKDOCS_ASSET_PATHS = [
  'packages/mkdocs-topoviewer/mkdocs_topoviewer/assets/topoviewer-embed.css',
  'packages/mkdocs-topoviewer/mkdocs_topoviewer/assets/topoviewer-embed.iife.js'
];

const ZENSICAL_GENERATED_PATHS = [
  'zensical.toml'
];

const GRAFANA_GENERATED_PATHS = [
  'packages/grafana-topoviewer-panel/src/generated/harnessFixtures.ts'
];

const args = process.argv.slice(2);
const remoteParity = args.includes('--remote-parity');
const selectedLane = parseLane(args);
const ciStartedAt = Date.now();
const laneTimings = [];
const stepTimings = [];

function parseLane(cliArgs) {
  const explicit = cliArgs.find((arg) => arg.startsWith('--lane='));
  if (explicit) {
    return explicit.slice('--lane='.length);
  }

  const laneFlagIndex = cliArgs.indexOf('--lane');
  if (laneFlagIndex !== -1) {
    return cliArgs[laneFlagIndex + 1];
  }

  return undefined;
}

function step(label, command, commandArgs, options = {}) {
  return {
    label,
    command,
    args: commandArgs,
    env: {
      ...(remoteParity ? { CI: 'true', NODE_ENV: 'test' } : {}),
      ...(options.env || {})
    }
  };
}

function checkGeneratedStep(label, paths, { sourceArea, projectionArea }) {
  return step(label, 'node', [
    'scripts/check-git-clean.mjs',
    '--source-area',
    sourceArea,
    '--projection-area',
    projectionArea,
    '--',
    ...paths
  ]);
}

const publicReadinessContractSteps = [
  step('lint documentation contract', 'npm', ['run', 'docs:lint']),
  step('check object reference drift', 'npm', ['run', 'check:object-reference']),
  step('audit curated examples', 'npm', ['run', 'examples:audit']),
  step('prepare renderer parity site assets', 'node', ['scripts/ensure-render-parity-assets.mjs']),
  step('check renderer surface parity', 'npm', ['run', 'render:parity']),
  step('run hostile-content tests', 'npm', ['run', 'test:hostile-content'])
];

const publicReadinessPackageSteps = [
  step('pack check', 'npm', ['run', 'pack:check']),
  step('check consumer install command', 'npm', ['run', 'install:check']),
  step('check MkDocs PyPI install command', 'npm', ['run', 'install:check:mkdocs']),
  step('build Grafana plugin artifact', 'npm', ['run', 'grafana:panel:build']),
  step('inspect package artifacts', 'npm', ['run', 'artifact:check:package'])
];

const publicReadinessSecuritySteps = [
  step('check dependency advisories', 'npm', ['run', 'dependency:advisories']),
  step('check Go vulnerabilities', 'npm', ['run', 'go:vulncheck'])
];

const publicReadinessFinalSteps = [
  step('write security health report', 'npm', ['run', 'security:health-report']),
  step('check public readiness guardrails', 'npm', ['run', 'check:public-readiness'])
];

const laneDefinitions = {
  env: [
    step('report environment', 'node', ['scripts/report-ci-environment.mjs'])
  ],
  generated: [
    step('sync docs', 'npm', ['run', 'sync:docs']),
    checkGeneratedStep('check generated docs are committed', GENERATED_DOC_PATHS, {
      sourceArea: 'packages/topoviewer/content/**, docs source templates, and README source content',
      projectionArea: 'README.md and docs/topoviewer/**'
    }),
    step('sync Grafana harness fixtures', 'npm', ['run', 'grafana:fixtures:sync']),
    checkGeneratedStep('check Grafana harness fixtures are committed', GRAFANA_GENERATED_PATHS, {
      sourceArea: 'packages/topoviewer/content/examples/** harness examples',
      projectionArea: 'packages/grafana-topoviewer-panel/src/generated/harnessFixtures.ts'
    })
  ],
  quality: [
    step('lint and typecheck', 'npm', ['run', 'quality'])
  ],
  schemas: [
    step('validate schemas', 'npm', ['run', 'validate:schemas']),
    step('validate semantics', 'npm', ['run', 'validate:semantics'])
  ],
  build: [
    step('build packages', 'npm', ['run', 'build']),
    step('sync MkDocs assets', 'npm', ['run', 'sync:mkdocs-assets']),
    checkGeneratedStep('check MkDocs assets are committed', MKDOCS_ASSET_PATHS, {
      sourceArea: 'packages/topoviewer/src/** and packages/topoviewer/dist/embed generated by sync:mkdocs-assets',
      projectionArea: 'packages/mkdocs-topoviewer/mkdocs_topoviewer/assets/**'
    })
  ],
  docs: [
    step('build packages for docs', 'npm', ['run', 'build']),
    step('sync MkDocs assets for docs', 'npm', ['run', 'sync:mkdocs-assets']),
    checkGeneratedStep('check MkDocs assets for docs are committed', MKDOCS_ASSET_PATHS, {
      sourceArea: 'packages/topoviewer/src/** and packages/topoviewer/dist/embed generated by sync:mkdocs-assets',
      projectionArea: 'packages/mkdocs-topoviewer/mkdocs_topoviewer/assets/**'
    }),
    step('sync documentation sources', 'npm', ['run', 'sync:docs']),
    checkGeneratedStep('check documentation sources are committed', GENERATED_DOC_PATHS, {
      sourceArea: 'packages/topoviewer/content/**, docs source templates, and README source content',
      projectionArea: 'README.md and docs/topoviewer/**'
    }),
    step('lint documentation contract', 'npm', ['run', 'docs:lint']),
    step('build MkDocs site', 'npm', ['run', 'docs:build:fast']),
    step('build Zensical site', 'npm', ['run', 'zensical:build'], { env: { TOPOVIEWER_ZENSICAL_SKIP_VIEWER_BUILD: '1' } }),
    checkGeneratedStep('check Zensical generated config is committed', ZENSICAL_GENERATED_PATHS, {
      sourceArea: 'docs-zensical/**, scripts/sync-zensical-docs.mjs, and Zensical docs configuration inputs',
      projectionArea: 'zensical.toml'
    }),
    step('build VS Code harness site', 'npm', ['run', 'vscode:harness:build']),
    step('check React authoring surface budgets', 'npm', ['run', 'react:perf:check:artifacts']),
    step('write Pages redirects', 'npm', ['run', 'pages:redirects']),
    step('prune publish-only docs artifacts', 'npm', ['run', 'docs:prune']),
    step('smoke built docs site', 'npm', ['run', 'docs:smoke']),
    step('inspect docs artifacts', 'npm', ['run', 'artifact:check:docs'])
  ],
  'render-parity': [
    step('check renderer surface parity', 'npm', ['run', 'render:parity'])
  ],
  'test:topoviewer': [
    step('test TopoViewer', 'npm', ['test'])
  ],
  'test:harness': [
    step('test VS Code harness', 'npm', ['run', 'test:vscode-harness'])
  ],
  'perf:smoke': [
    step('attention smoke benchmark', 'npm', ['run', 'benchmark:attention:smoke']),
    step('CLOS layout smoke benchmark', 'npm', ['run', 'benchmark:clos:smoke']),
    step('check Studio bundle budgets', 'npm', ['run', 'studio:benchmark:bundle'])
  ],
  package: [
    step('pack check', 'npm', ['run', 'pack:check']),
    step('check consumer install command', 'npm', ['run', 'install:check']),
    step('check MkDocs PyPI install command', 'npm', ['run', 'install:check:mkdocs']),
    step('build Grafana plugin artifact', 'npm', ['run', 'grafana:panel:build']),
    step('inspect package artifacts', 'npm', ['run', 'artifact:check:package']),
    step('build MkDocs wheel', 'npm', ['run', 'wheel:mkdocs']),
    step('inspect MkDocs wheel', 'npm', ['run', 'inspect:wheel'])
  ],
  'public-readiness:core': [
    ...publicReadinessContractSteps,
    ...publicReadinessFinalSteps
  ],
  'public-readiness': [
    ...publicReadinessContractSteps,
    ...publicReadinessPackageSteps,
    ...publicReadinessSecuritySteps,
    ...publicReadinessFinalSteps
  ]
};

const fullLaneOrder = [
  'env',
  'generated',
  'quality',
  'schemas',
  'build',
  'docs',
  'render-parity',
  'test:topoviewer',
  'test:harness',
  'perf:smoke',
  'package',
  'public-readiness'
];

if (args.includes('--list')) {
  console.log(fullLaneOrder.join('\n'));
  process.exit(0);
}

if (selectedLane && !laneDefinitions[selectedLane]) {
  console.error(`Unknown CI lane: ${selectedLane}`);
  console.error(`Available lanes: ${Object.keys(laneDefinitions).join(', ')}`);
  process.exit(2);
}

const lanesToRun = selectedLane ? [selectedLane] : fullLaneOrder;

for (const laneName of lanesToRun) {
  console.log(`\n# CI lane: ${laneName}`);
  const laneStartedAt = Date.now();
  for (const { label, command, args: commandArgs, env } of laneDefinitions[laneName]) {
    const result = runStep(label, command, commandArgs, env);
    stepTimings.push({
      laneName,
      label,
      commandLine: commandToString(command, commandArgs),
      durationMs: result.durationMs,
      status: result.ok ? 'success' : 'failure'
    });

    if (!result.ok) {
      laneTimings.push({
        laneName,
        durationMs: Date.now() - laneStartedAt,
        status: 'failure'
      });
      writeFailureSummary(laneName, label, commandToString(command, commandArgs), result.reason);
      writeTimingSummary();
      process.exit(result.exitCode);
    }
  }
  const laneDurationMs = Date.now() - laneStartedAt;
  laneTimings.push({
    laneName,
    durationMs: laneDurationMs,
    status: 'success'
  });
  console.log(`\n# CI lane completed: ${laneName} (${formatDuration(laneDurationMs)})`);
}

writeTimingSummary();

function runStep(label, command, commandArgs, extraEnv = {}) {
  console.log(`\n==> ${label}`);
  const startedAt = Date.now();
  const result = spawnSync(command, commandArgs, {
    env: {
      ...process.env,
      ...extraEnv
    },
    shell: process.platform === 'win32',
    stdio: 'inherit'
  });

  if (result.error) {
    console.error(result.error.message);
    return {
      ok: false,
      reason: result.error.message,
      exitCode: 1,
      durationMs: Date.now() - startedAt
    };
  }

  if (result.signal) {
    console.error(`${label} terminated with signal ${result.signal}.`);
    return {
      ok: false,
      reason: `terminated with signal ${result.signal}`,
      exitCode: 1,
      durationMs: Date.now() - startedAt
    };
  }

  if (result.status !== 0) {
    return {
      ok: false,
      reason: `exited with status ${result.status ?? 1}`,
      exitCode: result.status ?? 1,
      durationMs: Date.now() - startedAt
    };
  }

  const durationMs = Date.now() - startedAt;
  console.log(`==> ${label} completed in ${formatDuration(durationMs)}`);
  return {
    ok: true,
    durationMs
  };
}

function writeFailureSummary(laneName, label, commandLine, reason) {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryPath) {
    return;
  }
  fs.appendFileSync(summaryPath, [
    '## TopoViewer CI Failure',
    '',
    `- Lane: \`${laneName}\``,
    `- Step: \`${label}\``,
    `- Command: \`${commandLine}\``,
    `- Reason: ${reason}`,
    '',
    'Run the same command locally from the repository root with Node.js 24 LTS.',
    ''
  ].join('\n'));
}

function writeTimingSummary() {
  printTimingSummary();

  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryPath) {
    return;
  }

  fs.appendFileSync(summaryPath, [
    '## TopoViewer CI Timing',
    '',
    `Total elapsed: ${formatDuration(Date.now() - ciStartedAt)}`,
    '',
    '### Lanes',
    '',
    '| Lane | Status | Duration |',
    '| --- | --- | ---: |',
    ...laneTimings.map(({ laneName, status, durationMs }) => (
      `| \`${laneName}\` | ${status} | ${formatDuration(durationMs)} |`
    )),
    '',
    '### Steps',
    '',
    '| Lane | Step | Status | Duration |',
    '| --- | --- | --- | ---: |',
    ...stepTimings.map(({ laneName, label, status, durationMs }) => (
      `| \`${laneName}\` | ${escapeMarkdownTableCell(label)} | ${status} | ${formatDuration(durationMs)} |`
    )),
    ''
  ].join('\n'));
}

function printTimingSummary() {
  console.log('\n# CI timing summary');
  console.log(`Total elapsed: ${formatDuration(Date.now() - ciStartedAt)}`);
  for (const { laneName, status, durationMs } of laneTimings) {
    console.log(`- ${laneName}: ${status}, ${formatDuration(durationMs)}`);
  }
}

function commandToString(command, commandArgs) {
  return [command, ...commandArgs].join(' ');
}

function formatDuration(durationMs) {
  if (durationMs < 1000) {
    return `${durationMs}ms`;
  }

  const totalSeconds = durationMs / 1000;
  if (totalSeconds < 60) {
    return `${totalSeconds.toFixed(1)}s`;
  }

  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds - (minutes * 60);
  return `${minutes}m ${seconds.toFixed(1)}s`;
}

function escapeMarkdownTableCell(value) {
  return value.replaceAll('|', '\\|');
}
