import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { exampleFileKeys, sourceFileFor } from './lib/content-examples.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packageRoot = path.join(repoRoot, 'packages/topoviewer');
const contentRoot = path.join(packageRoot, 'content');
const contentPagesRoot = path.join(contentRoot, 'pages');
const contentExamplesRoot = path.join(contentRoot, 'examples');
const contentFragmentsRoot = path.join(contentPagesRoot, '_fragments');
const packageDocsRoot = path.join(packageRoot, 'docs');
const packageExamplesRoot = path.join(packageRoot, 'examples');
const packageTestCasesRoot = path.join(packageExamplesRoot, 'test-cases');
const packageStressRoot = path.join(packageExamplesRoot, 'stress');
const docsRoot = path.resolve(process.env.TOPOVIEWER_DOCS_ROOT || path.join(repoRoot, 'docs'));
const checkOnly = process.argv.includes('--check');

function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function readYaml(filePath) {
  return yaml.load(readText(filePath)) || {};
}

function dumpYaml(document) {
  return yaml.dump(document, {
    lineWidth: 120,
    noRefs: true,
    quotingType: '"'
  });
}

function toPosix(value) {
  return value.split(path.sep).join(path.posix.sep);
}

function relative(filePath) {
  return toPosix(path.relative(repoRoot, filePath));
}

function fail(message) {
  console.error(message);
  process.exitCode = 1;
}

function writeTextIfChanged(filePath, content) {
  const existing = fs.existsSync(filePath) ? readText(filePath) : undefined;
  if (existing === content) return false;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  return true;
}

function projectText(filePath, content, label) {
  if (checkOnly) {
    const existing = fs.existsSync(filePath) ? readText(filePath) : undefined;
    if (existing !== content) {
      fail(`${label} is out of sync: ${relative(filePath)}`);
    }
    return false;
  }

  if (writeTextIfChanged(filePath, content)) {
    console.log(`generated ${relative(filePath)}`);
    return true;
  }
  return false;
}

function listFiles(dirPath) {
  if (!fs.existsSync(dirPath)) return [];
  const files = [];
  for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
    const absolute = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...listFiles(absolute));
    } else if (entry.isFile()) {
      files.push(absolute);
    }
  }
  return files;
}

function removeStaleFiles(root, expectedFiles, label) {
  const expected = new Set([...expectedFiles].map((filePath) => path.resolve(filePath)));
  for (const filePath of listFiles(root)) {
    if (expected.has(path.resolve(filePath))) continue;
    if (checkOnly) {
      fail(`${label} has stale generated file: ${relative(filePath)}`);
    } else {
      fs.rmSync(filePath);
      console.log(`removed stale ${relative(filePath)}`);
    }
  }
}

function fragment(name) {
  return readText(path.join(contentFragmentsRoot, name)).trim();
}

function generatedNotice(source) {
  return `<!-- Generated from ${source}. Do not edit this file directly. -->`;
}

function readmeMarkdown() {
  const positioning = fragment('product-positioning.md');
  const integrations = fragment('integration-surfaces.md');
  return `${generatedNotice('packages/topoviewer/content/pages/_fragments/*.md')}
# TopoViewer

[![CI](https://github.com/asadarafat/TopoViewer/actions/workflows/ci.yml/badge.svg)](https://github.com/asadarafat/TopoViewer/actions/workflows/ci.yml)
[![Docs](https://github.com/asadarafat/TopoViewer/actions/workflows/docs.yml/badge.svg)](https://github.com/asadarafat/TopoViewer/actions/workflows/docs.yml)

${positioning}

![TopoViewer YAML to rendered network diagram](docs/assets/topoviewer-yaml-to-diagram.png)

## Why It Matters

Topology diagrams drift when they are maintained as static images. TopoViewer
keeps topology as reviewable code, so the same model can render documentation,
product views, authoring previews, exported diagrams, and CI-backed examples.

## First Result

\`\`\`bash
git clone https://github.com/asadarafat/TopoViewer.git
cd TopoViewer
npm ci
npm run docs:preview
\`\`\`

Open:

- MkDocs: \`http://127.0.0.1:8001/TopoViewer/\`
- Zensical: \`http://127.0.0.1:8002/TopoViewer/zensical/\`
- Harness: run \`npm run vscode:harness\` and open the printed URL

## Integration Surfaces

${integrations}

## Quick Links

- [Published docs](https://asadarafat.github.io/TopoViewer/)
- [Why TopoViewer](docs/topoviewer/why-topoviewer.md)
- [YAML to diagram](docs/topoviewer/yaml-to-diagram/index.md)
- [Real network demo](docs/topoviewer/real-network-demo.md)
- [Attention examples](docs/topoviewer/reference/attention/index.md)
- [Integration roadmap](docs/topoviewer/integration-roadmap.md)
- [Browser authoring harness](https://asadarafat.github.io/TopoViewer/harness/)

## Development

Prerequisites:

- Node.js 24 LTS
- Python 3.9+ for MkDocs and Zensical workflows

\`\`\`bash
npm ci
npm run sync:content
npm run ci
\`\`\`

Content edits start in \`packages/topoviewer/content/**\`. Generated package
docs/examples, MkDocs pages, Zensical pages, and this README are projections.

## Package Layout

- \`packages/topoviewer\` - React renderer, compiler, schemas, examples, and browser embed bundle
- \`packages/mkdocs-topoviewer\` - MkDocs plugin and vendored viewer assets
- \`packages/vscode-topoviewer\` - experimental VS Code extension and browser harness

## Legacy History

The historical pre-refresh repository is preserved at
[topoViewer-legacy](https://github.com/asadarafat/topoViewer-legacy).
`;
}

function docsIndexMarkdown() {
  const positioning = fragment('product-positioning.md');
  const integrations = fragment('integration-surfaces.md');
  return `${generatedNotice('packages/topoviewer/content/pages/_fragments/*.md')}
# TopoViewer

${positioning}

![TopoViewer YAML to rendered network diagram](assets/topoviewer-yaml-to-diagram.png)

## Explore

- [Why TopoViewer?](topoviewer/why-topoviewer.md)
- [YAML to diagram](topoviewer/yaml-to-diagram/index.md)
- [Real network demo](topoviewer/real-network-demo.md)
- [Integration roadmap](topoviewer/integration-roadmap.md)
- [Authoring model](topoviewer/authoring.md)
- [Reference model](topoviewer/reference-model.md)
- [Stylesheet](topoviewer/stylesheet.md)
- [Topology attention](topoviewer/attention.md)
- [MkDocs embed](topoviewer/mkdocs.md)
- [Zensical adapter](topoviewer/zensical.md)
- [Production hardening](topoviewer/production.md)

## Surfaces

${integrations}

## Examples

The feature examples are generated from
\`packages/topoviewer/content/examples\`. Each example is both documentation
and a Playwright-backed test fixture.
`;
}

function projectPages() {
  const expectedPackageDocs = new Set();

  for (const source of listFiles(contentPagesRoot)) {
    const sourceRelative = path.relative(contentPagesRoot, source);
    if (sourceRelative.split(path.sep)[0] === '_fragments') continue;
    if (!source.endsWith('.md')) continue;
    const target = path.join(packageDocsRoot, sourceRelative);
    expectedPackageDocs.add(target);
    projectText(target, readText(source), `package doc ${sourceRelative}`);
  }

  removeStaleFiles(packageDocsRoot, expectedPackageDocs, 'package docs projection');
  projectText(path.join(repoRoot, 'README.md'), readmeMarkdown(), 'root README');
  projectText(path.join(docsRoot, 'index.md'), docsIndexMarkdown(), 'docs home');
}

function projectedCatalog(catalog) {
  return {
    version: catalog.version,
    examples: (catalog.examples || []).map((example) => {
      const { sourcePath: _sourcePath, sourceFiles: _sourceFiles, ...publicExample } = example;
      return publicExample;
    })
  };
}

function projectExampleFile(example, fileName, expectedPackageFiles) {
  const source = sourceFileFor(contentExamplesRoot, example, fileName);
  if (!fs.existsSync(source)) {
    throw new Error(`Example ${example.id} source file is missing: ${relative(source)}`);
  }
  const target = path.join(packageTestCasesRoot, example.path, fileName);
  expectedPackageFiles.add(target);
  projectText(target, readText(source), `${example.id} ${fileName}`);
}

function projectStressExamples(expectedPackageFiles) {
  const stressSourceRoot = path.join(contentExamplesRoot, 'stress');
  if (!fs.existsSync(stressSourceRoot)) return;

  for (const source of listFiles(stressSourceRoot)) {
    const sourceRelative = path.relative(stressSourceRoot, source);
    const target = path.join(packageStressRoot, sourceRelative);
    expectedPackageFiles.add(target);
    projectText(target, readText(source), `stress example ${sourceRelative}`);
  }
}

function projectExamples() {
  const catalogFile = path.join(contentExamplesRoot, 'catalog.yaml');
  if (!fs.existsSync(catalogFile)) {
    throw new Error(`Canonical content catalog is missing: ${relative(catalogFile)}`);
  }

  const catalog = readYaml(catalogFile);
  const expectedPackageFiles = new Set();
  const generatedCatalogFile = path.join(packageTestCasesRoot, 'catalog.yaml');
  expectedPackageFiles.add(generatedCatalogFile);
  projectText(generatedCatalogFile, dumpYaml(projectedCatalog(catalog)), 'package examples catalog');

  for (const example of catalog.examples || []) {
    for (const fileName of Object.keys(exampleFileKeys)) {
      projectExampleFile(example, fileName, expectedPackageFiles);
    }
  }

  removeStaleFiles(packageTestCasesRoot, expectedPackageFiles, 'package test-case projection');

  const expectedStressFiles = new Set();
  projectStressExamples(expectedStressFiles);
  removeStaleFiles(packageStressRoot, expectedStressFiles, 'package stress projection');
}

projectPages();
projectExamples();

if (process.exitCode) {
  process.exit(process.exitCode);
}

console.log(checkOnly ? 'content projections are in sync' : 'content projections synced');
