import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packageRoot = path.join(repoRoot, 'packages/topoviewer');
const contentRoot = path.join(packageRoot, 'content');
const contentPagesRoot = path.join(contentRoot, 'pages');
const contentFragmentsRoot = path.join(contentPagesRoot, '_fragments');
const docsRoot = path.resolve(process.env.TOPOVIEWER_DOCS_ROOT || path.join(repoRoot, 'docs'));
const checkOnly = process.argv.includes('--check');
const allowDirtyProjectionOverwrite = process.env.TOPOVIEWER_SYNC_ALLOW_DIRTY_PROJECTIONS === '1';

function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function toPosix(value) {
  return value.split(path.sep).join(path.posix.sep);
}

function relative(filePath) {
  return toPosix(path.relative(repoRoot, filePath));
}

function fail(message) {
  console.error(message);
  process.exitCode = 1;
}

function writeTextIfChanged(filePath, content) {
  const existing = fs.existsSync(filePath) ? readText(filePath) : undefined;
  if (existing === content) return false;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  return true;
}

function isGitDirty(filePath) {
  try {
    const output = execFileSync('git', ['status', '--porcelain', '--', path.relative(repoRoot, filePath)], {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    });
    return output.trim().length > 0;
  } catch {
    return false;
  }
}

function assertProjectionCanBeOverwritten(filePath, content, label, source) {
  if (checkOnly || allowDirtyProjectionOverwrite || !source || !fs.existsSync(filePath)) return;
  if (readText(filePath) === content) return;
  if (!isGitDirty(filePath) || isGitDirty(source)) return;

  throw new Error([
    `Refusing to overwrite dirty generated content projection: ${relative(filePath)}`,
    `Projection: ${label}`,
    `Canonical source: ${relative(source)}`,
    '',
    'Edit the canonical source under packages/topoviewer/content/**, then run:',
    '  npm run sync:docs',
    '',
    'If this projected file was changed by mistake, revert or discard that generated-file edit first.',
    'To force regeneration anyway, rerun with TOPOVIEWER_SYNC_ALLOW_DIRTY_PROJECTIONS=1.'
  ].join('\n'));
}

function projectText(filePath, content, label, source) {
  if (checkOnly) {
    const existing = fs.existsSync(filePath) ? readText(filePath) : undefined;
    if (existing !== content) {
      fail(`${label} is out of sync: ${relative(filePath)}`);
    }
    return false;
  }

  assertProjectionCanBeOverwritten(filePath, content, label, source);
  if (writeTextIfChanged(filePath, content)) {
    console.log(`generated ${relative(filePath)}`);
    return true;
  }
  return false;
}

function fragment(name) {
  return readText(path.join(contentFragmentsRoot, name)).trim();
}

function generatedNotice(source) {
  return `<!-- Generated from ${source}. Do not edit this file directly. -->`;
}

function readmeMarkdown() {
  return `${generatedNotice('packages/topoviewer/content/pages/_fragments/readme.md')}
${fragment('readme.md')}
`;
}

function docsIndexMarkdown() {
  const positioning = fragment('product-positioning.md');
  const integrations = fragment('integration-surfaces.md');
  const supportStatuses = fragment('support-statuses.md');
  return `${generatedNotice('packages/topoviewer/content/pages/_fragments/*.md')}
# TopoViewer

${positioning}

![TopoViewer YAML to rendered network diagram](assets/topoviewer-yaml-to-diagram.png)

## Start In 60 Seconds

\`\`\`bash
npm install topoviewer @xyflow/react react react-dom
\`\`\`

1. Render the copyable YAML pair in [First Topology](topoviewer/start/first-topology.md).
2. Style it with [Style Your First Topology](topoviewer/start/style-your-first-topology.md).
3. Embed it in [React](topoviewer/examples/use-cases/react.md) or [MkDocs](topoviewer/examples/use-cases/mkdocs.md).

## Choose A Path

| Need | Start here |
|---|---|
| Understand the product | [Why TopoViewer](topoviewer/start/why-topoviewer.md) |
| Author a topology | [First Topology](topoviewer/start/first-topology.md) |
| Style a topology | [Style Your First Topology](topoviewer/start/style-your-first-topology.md) |
| Explore examples | [Examples](topoviewer/examples/index.md) |
| Embed in a React product | [React](topoviewer/examples/use-cases/react.md) and [TypeScript API](topoviewer/reference/typescript-api.md) |
| Embed in documentation | [MkDocs](topoviewer/examples/use-cases/mkdocs.md) or [Static HTML / Zensical Adapter](topoviewer/examples/use-cases/static-html-zensical-adapter.md) |
| Operate from telemetry | [Grafana TopoViewer Containerlab Lab](topoviewer/examples/use-cases/grafana-topoviewer-containerlab-lab.md) |
| Reference accepted contracts | [Object attributes](topoviewer/reference/object-attributes.md), [YAML schemas](topoviewer/reference/yaml-schemas.md), [compatibility](topoviewer/reference/compatibility.md), and [stylesheet reference](topoviewer/reference/stylesheet-reference.md) |
| Evaluate architecture and risk | [Architecture](topoviewer/evaluate/architecture.md), [threat model](topoviewer/evaluate/threat-model.md), [performance and accessibility](topoviewer/evaluate/performance-reliability-accessibility.md), and [Adopt TopoViewer Or Keep Topology Locked To A Surface](topoviewer/evaluate/adopt-topoviewer-or-keep-topology-locked-to-a-surface.md) |
| Maintain or release the repo | [Production Hardening](topoviewer/maintainers/production-hardening.md), [Design Review Checklist](topoviewer/maintainers/design-review-checklist.md), [Release](topoviewer/maintainers/release.md), and [Documentation Standard](topoviewer/maintainers/documentation-standard.md) |
| Debug a broken render | [Debug Rendering](topoviewer/author/debug-rendering.md) |

## Integration Surfaces

${integrations}

## Support Status Labels

${supportStatuses}

## Examples

The feature examples are generated from
\`packages/topoviewer/content/examples\`. Each example is both documentation
and a Playwright-backed test fixture.

- [Examples](topoviewer/examples/index.md)
- [Generated feature catalog](topoviewer/examples/graph/index.md)
- [Service Provider Network](topoviewer/examples/use-cases/service-provider-network.md)
- [CLOS layout examples](topoviewer/examples/layout/index.md)
`;
}

function projectPages() {
  projectText(path.join(repoRoot, 'README.md'), readmeMarkdown(), 'root README', contentPagesRoot);
  projectText(path.join(docsRoot, 'index.md'), docsIndexMarkdown(), 'docs home', contentPagesRoot);
}

projectPages();

if (process.exitCode) {
  process.exit(process.exitCode);
}

console.log(checkOnly ? 'content projections are in sync' : 'content projections synced');
