import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { exampleFileKeys, sourceFileFor } from './lib/content-examples.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packageRoot = path.join(repoRoot, 'packages/topoviewer');
const contentRoot = path.join(packageRoot, 'content');
const contentPagesRoot = path.join(contentRoot, 'pages');
const contentExamplesRoot = path.join(contentRoot, 'examples');
const contentFragmentsRoot = path.join(contentPagesRoot, '_fragments');
const packageDocsRoot = path.join(packageRoot, 'docs');
const packageExamplesRoot = path.join(packageRoot, 'examples');
const packageTestCasesRoot = path.join(packageExamplesRoot, 'test-cases');
const packageStressRoot = path.join(packageExamplesRoot, 'stress');
const docsRoot = path.resolve(process.env.TOPOVIEWER_DOCS_ROOT || path.join(repoRoot, 'docs'));
const checkOnly = process.argv.includes('--check');

function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function readYaml(filePath) {
  return yaml.load(readText(filePath)) || {};
}

function dumpYaml(document) {
  return yaml.dump(document, {
    lineWidth: 120,
    noRefs: true,
    quotingType: '"'
  });
}

function toPosix(value) {
  return value.split(path.sep).join(path.posix.sep);
}

function relative(filePath) {
  return toPosix(path.relative(repoRoot, filePath));
}

function fail(message) {
  console.error(message);
  process.exitCode = 1;
}

function writeTextIfChanged(filePath, content) {
  const existing = fs.existsSync(filePath) ? readText(filePath) : undefined;
  if (existing === content) return false;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  return true;
}

function projectText(filePath, content, label) {
  if (checkOnly) {
    const existing = fs.existsSync(filePath) ? readText(filePath) : undefined;
    if (existing !== content) {
      fail(`${label} is out of sync: ${relative(filePath)}`);
    }
    return false;
  }

  if (writeTextIfChanged(filePath, content)) {
    console.log(`generated ${relative(filePath)}`);
    return true;
  }
  return false;
}

function listFiles(dirPath) {
  if (!fs.existsSync(dirPath)) return [];
  const files = [];
  for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
    const absolute = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...listFiles(absolute));
    } else if (entry.isFile()) {
      files.push(absolute);
    }
  }
  return files;
}

function removeStaleFiles(root, expectedFiles, label) {
  const expected = new Set([...expectedFiles].map((filePath) => path.resolve(filePath)));
  for (const filePath of listFiles(root)) {
    if (expected.has(path.resolve(filePath))) continue;
    if (checkOnly) {
      fail(`${label} has stale generated file: ${relative(filePath)}`);
    } else {
      fs.rmSync(filePath);
      console.log(`removed stale ${relative(filePath)}`);
    }
  }
}

function fragment(name) {
  return readText(path.join(contentFragmentsRoot, name)).trim();
}

function generatedNotice(source) {
  return `<!-- Generated from ${source}. Do not edit this file directly. -->`;
}

function readmeMarkdown() {
  const positioning = fragment('product-positioning.md');
  const integrations = fragment('integration-surfaces.md');
  const supportStatuses = fragment('support-statuses.md');
  return `${generatedNotice('packages/topoviewer/content/pages/_fragments/*.md')}
# TopoViewer

[![CI](https://github.com/asadarafat/topoviewer/actions/workflows/ci.yml/badge.svg)](https://github.com/asadarafat/topoviewer/actions/workflows/ci.yml)
[![Docs](https://github.com/asadarafat/topoviewer/actions/workflows/docs.yml/badge.svg)](https://github.com/asadarafat/topoviewer/actions/workflows/docs.yml)

${positioning}

The stable core is deliberately small:

- \`topology.yaml\` describes objects and relationships.
- \`stylesheet.yaml\` describes presentation with selectors.
- \`TopoViewer\` renders an interactive diagram that can be embedded in docs,
  React products, authoring tools, and operational dashboards.

[![Same TopoViewer YAML rendered in Harness, MkDocs, Zensical, and Grafana](docs/assets/topoviewer-yaml-to-graph-collage.png)](https://asadarafat.github.io/topoviewer/harness/)

## Why It Matters

Topology diagrams drift when they are maintained as static images. TopoViewer
keeps topology as reviewable code, so the same model can render documentation,
product views, authoring previews, exported diagrams, and CI-backed examples.

## First Result

\`\`\`bash
git clone https://github.com/asadarafat/topoviewer.git
cd topoviewer
npm ci
npm run docs:preview
\`\`\`

Open:

- MkDocs: \`http://127.0.0.1:8001/topoviewer/docs/mkdocs/\`
- Zensical: \`http://127.0.0.1:8001/topoviewer/docs/zensical/\`
- Browser Harness: \`http://127.0.0.1:8001/topoviewer/harness/\`

The smallest useful YAML pair is in the
[First topology guide](https://asadarafat.github.io/topoviewer/docs/mkdocs/topoviewer/start/first-topology/).

## Integration Surfaces

${integrations}

## Support Status Labels

${supportStatuses}

## Quick Links

- [Published MkDocs](https://asadarafat.github.io/topoviewer/docs/mkdocs/)
- [Published Zensical](https://asadarafat.github.io/topoviewer/docs/zensical/)
- [Why TopoViewer](https://asadarafat.github.io/topoviewer/docs/mkdocs/topoviewer/start/why-topoviewer/)
- [Browser Harness](https://asadarafat.github.io/topoviewer/harness/)
- [Integration Roadmap](https://asadarafat.github.io/topoviewer/docs/mkdocs/topoviewer/evaluate/integration-roadmap/)

## Development

Prerequisites:

- Node.js 24 LTS
- Python 3.9+ for MkDocs and Zensical workflows

\`\`\`bash
npm ci
npm run sync:content
npm run ci
\`\`\`

Content edits start in \`packages/topoviewer/content/**\`. Generated package
docs/examples, MkDocs pages, Zensical pages, and this README are projections.

## Legacy History

The historical pre-refresh repository is preserved at
[topoViewer-legacy](https://github.com/asadarafat/topoViewer-legacy).
`;
}

function docsIndexMarkdown() {
  const positioning = fragment('product-positioning.md');
  const integrations = fragment('integration-surfaces.md');
  const supportStatuses = fragment('support-statuses.md');
  return `${generatedNotice('packages/topoviewer/content/pages/_fragments/*.md')}
# TopoViewer

${positioning}

![TopoViewer YAML to rendered network diagram](assets/topoviewer-yaml-to-diagram.png)

## Choose A Path

| Need | Start here |
|---|---|
| Understand the product | [Why TopoViewer](topoviewer/start/why-topoviewer.md) |
| Author a topology | [First Topology](topoviewer/start/first-topology.md) |
| Style a topology | [Style Your First Topology](topoviewer/start/style-your-first-topology.md) |
| Explore examples | [Examples Gallery](topoviewer/examples/examples-gallery.md) |
| Embed in a React product | [React](topoviewer/embed/react.md) and [TypeScript API](topoviewer/reference/typescript-api.md) |
| Embed in documentation | [MkDocs](topoviewer/embed/mkdocs.md) or [Static HTML / Zensical Adapter](topoviewer/embed/static-html-zensical-adapter.md) |
| Operate from telemetry | [Grafana](topoviewer/labs/grafana.md) and [Grafana Mapper Recipes](topoviewer/labs/grafana-mapper-recipes.md) |
| Reference accepted contracts | [Object attributes](topoviewer/reference/object-attributes.md), [YAML schemas](topoviewer/reference/yaml-schemas.md), [compatibility](topoviewer/reference/compatibility.md), and [stylesheet reference](topoviewer/reference/stylesheet-reference.md) |
| Evaluate architecture and risk | [Architecture](topoviewer/evaluate/architecture.md), [threat model](topoviewer/evaluate/threat-model.md), [performance and accessibility](topoviewer/evaluate/performance-reliability-accessibility.md), and [Build Or Adopt](topoviewer/evaluate/build-or-adopt.md) |
| Maintain or release the repo | [Production Hardening](topoviewer/maintainers/production-hardening.md), [Design Review Checklist](topoviewer/maintainers/design-review-checklist.md), [Release](topoviewer/maintainers/release.md), and [Documentation Standard](topoviewer/maintainers/documentation-standard.md) |
| Debug a broken render | [Debug Rendering](topoviewer/author/debug-rendering.md) |

## Integration Surfaces

${integrations}

## Support Status Labels

${supportStatuses}

## Examples

The feature examples are generated from
\`packages/topoviewer/content/examples\`. Each example is both documentation
and a Playwright-backed test fixture.

- [Examples Gallery](topoviewer/examples/examples-gallery.md)
- [Generated feature catalog](topoviewer/reference/graph/index.md)
- [Real Network Demo](topoviewer/examples/real-network-demo.md)
- [CLOS layout examples](topoviewer/reference/layout/index.md)
`;
}

function projectPages() {
  const expectedPackageDocs = new Set();

  for (const source of listFiles(contentPagesRoot)) {
    const sourceRelative = path.relative(contentPagesRoot, source);
    if (sourceRelative.split(path.sep)[0] === '_fragments') continue;
    if (!source.endsWith('.md')) continue;
    const target = path.join(packageDocsRoot, sourceRelative);
    expectedPackageDocs.add(target);
    projectText(target, readText(source), `package doc ${sourceRelative}`);
  }

  removeStaleFiles(packageDocsRoot, expectedPackageDocs, 'package docs projection');
  projectText(path.join(repoRoot, 'README.md'), readmeMarkdown(), 'root README');
  projectText(path.join(docsRoot, 'index.md'), docsIndexMarkdown(), 'docs home');
}

function projectedCatalog(catalog) {
  return {
    version: catalog.version,
    examples: (catalog.examples || []).map((example) => {
      const { sourcePath: _sourcePath, sourceFiles: _sourceFiles, ...publicExample } = example;
      return publicExample;
    })
  };
}

function projectExampleFile(example, fileName, expectedPackageFiles) {
  const source = sourceFileFor(contentExamplesRoot, example, fileName);
  if (!fs.existsSync(source)) {
    throw new Error(`Example ${example.id} source file is missing: ${relative(source)}`);
  }
  const target = path.join(packageTestCasesRoot, example.path, fileName);
  expectedPackageFiles.add(target);
  projectText(target, readText(source), `${example.id} ${fileName}`);
}

function projectStressExamples(expectedPackageFiles) {
  const stressSourceRoot = path.join(contentExamplesRoot, 'stress');
  if (!fs.existsSync(stressSourceRoot)) return;

  for (const source of listFiles(stressSourceRoot)) {
    const sourceRelative = path.relative(stressSourceRoot, source);
    const target = path.join(packageStressRoot, sourceRelative);
    expectedPackageFiles.add(target);
    projectText(target, readText(source), `stress example ${sourceRelative}`);
  }
}

function projectExamples() {
  const catalogFile = path.join(contentExamplesRoot, 'catalog.yaml');
  if (!fs.existsSync(catalogFile)) {
    throw new Error(`Canonical content catalog is missing: ${relative(catalogFile)}`);
  }

  const catalog = readYaml(catalogFile);
  const expectedPackageFiles = new Set();
  const generatedCatalogFile = path.join(packageTestCasesRoot, 'catalog.yaml');
  expectedPackageFiles.add(generatedCatalogFile);
  projectText(generatedCatalogFile, dumpYaml(projectedCatalog(catalog)), 'package examples catalog');

  for (const example of catalog.examples || []) {
    for (const fileName of Object.keys(exampleFileKeys)) {
      projectExampleFile(example, fileName, expectedPackageFiles);
    }
  }

  removeStaleFiles(packageTestCasesRoot, expectedPackageFiles, 'package test-case projection');

  const expectedStressFiles = new Set();
  projectStressExamples(expectedStressFiles);
  removeStaleFiles(packageStressRoot, expectedStressFiles, 'package stress projection');
}

projectPages();
projectExamples();

if (process.exitCode) {
  process.exit(process.exitCode);
}

console.log(checkOnly ? 'content projections are in sync' : 'content projections synced');
