// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseAssets(arg1) {
  return window['go']['main']['DesktopApp']['ChooseAssets'](arg1);
}

export function CommitFiles(arg1) {
  return window['go']['main']['DesktopApp']['CommitFiles'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['DesktopApp']['CopyText'](arg1);
}

export function ExportArtifact(arg1) {
  return window['go']['main']['DesktopApp']['ExportArtifact'](arg1);
}

export function ForgetRecentProject(arg1) {
  return window['go']['main']['DesktopApp']['ForgetRecentProject'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['DesktopApp']['ListFiles'](arg1);
}

export function NewUntitledProject() {
  return window['go']['main']['DesktopApp']['NewUntitledProject']();
}

export function OpenProjectFolder() {
  return window['go']['main']['DesktopApp']['OpenProjectFolder']();
}

export function PromoteRecentProject(arg1) {
  return window['go']['main']['DesktopApp']['PromoteRecentProject'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ReadFile'](arg1, arg2);
}

export function ReadPreference(arg1) {
  return window['go']['main']['DesktopApp']['ReadPreference'](arg1);
}

export function ReadRecovery(arg1) {
  return window['go']['main']['DesktopApp']['ReadRecovery'](arg1);
}

export function ReleaseProject(arg1) {
  return window['go']['main']['DesktopApp']['ReleaseProject'](arg1);
}

export function Revision(arg1) {
  return window['go']['main']['DesktopApp']['Revision'](arg1);
}

export function SaveUntitledProject(arg1) {
  return window['go']['main']['DesktopApp']['SaveUntitledProject'](arg1);
}

export function StartupProject() {
  return window['go']['main']['DesktopApp']['StartupProject']();
}

export function UnwatchProject(arg1) {
  return window['go']['main']['DesktopApp']['UnwatchProject'](arg1);
}

export function WatchProject(arg1) {
  return window['go']['main']['DesktopApp']['WatchProject'](arg1);
}

export function WritePreference(arg1, arg2) {
  return window['go']['main']['DesktopApp']['WritePreference'](arg1, arg2);
}

export function WriteRecovery(arg1, arg2) {
  return window['go']['main']['DesktopApp']['WriteRecovery'](arg1, arg2);
}
