// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseAssets(arg1:main.AssetRequest):Promise<main.AssetsResponse>;

export function CommitFiles(arg1:main.CommitFilesRequest):Promise<main.RevisionResponse>;

export function CopyText(arg1:string):Promise<main.EmptyResponse>;

export function ExportArtifact(arg1:main.ArtifactRequest):Promise<main.EmptyResponse>;

export function ForgetRecentProject(arg1:string):Promise<main.EmptyResponse>;

export function ListFiles(arg1:string):Promise<main.FilesResponse>;

export function NewUntitledProject():Promise<main.ProjectResponse>;

export function OpenProjectFolder():Promise<main.ProjectResponse>;

export function PromoteRecentProject(arg1:string):Promise<main.EmptyResponse>;

export function ReadFile(arg1:string,arg2:string):Promise<main.BytesResponse>;

export function ReadPreference(arg1:string):Promise<main.ValueResponse>;

export function ReadRecovery(arg1:string):Promise<main.ValueResponse>;

export function ReleaseProject(arg1:string):Promise<main.EmptyResponse>;

export function Revision(arg1:string):Promise<main.RevisionResponse>;

export function SaveUntitledProject(arg1:main.CommitFilesRequest):Promise<main.ProjectResponse>;

export function StartupProject():Promise<main.ProjectResponse>;

export function UnwatchProject(arg1:string):Promise<main.EmptyResponse>;

export function WatchProject(arg1:string):Promise<main.EmptyResponse>;

export function WritePreference(arg1:string,arg2:string):Promise<main.EmptyResponse>;

export function WriteRecovery(arg1:string,arg2:string):Promise<main.EmptyResponse>;
