export const starterAuthoringTopologyText = [
  'layout:',
  '  mode: manual',
  '  width: 900',
  '  height: 520',
  'graph:',
  '  id: custom-topology',
  '  layers:',
  '    - id: physical',
  '      name: Physical',
  '    - id: paths',
  '      name: Paths',
  '    - id: annotations',
  '      name: Annotations',
  '  nodes: []',
  '  links: []',
  '  paths: []',
  '  regions: []',
  ''
].join('\n');

export const starterAuthoringStylesheetText = [
  'icons:',
  '  node.generic:',
  '    glyph: N',
  '    fill: "#263238"',
  '    stroke: "#90a4ae"',
  '  router.generic:',
  '    glyph: R',
  '    fill: "#1565c0"',
  '    stroke: "#90caf9"',
  '  service.generic:',
  '    glyph: SVC',
  '    fill: "#2e7d32"',
  '    stroke: "#a5d6a7"',
  '  controller.generic:',
  '    glyph: CTL',
  '    fill: "#6a1b9a"',
  '    stroke: "#ce93d8"',
  '  external.generic:',
  '    glyph: EXT',
  '    fill: "#455a64"',
  '    stroke: "#b0bec5"',
  'labelFields:',
  '  - name',
  'stylesheet:',
  '  - selector: node',
  '    style:',
  '      icon: node.generic',
  '      shape: roundRectangle',
  '      width: 104',
  '      height: 58',
  '      borderWidth: 2',
  '      labelFontWeight: 800',
  '      labelColor: var(--topoviewer-fg-strong)',
  '      labelBackgroundColor: var(--topoviewer-panel-bg)',
  '      labelBackgroundOpacity: 0.92',
  '      labelPadding: 4',
  '      metaColor: var(--topoviewer-fg-muted)',
  '  - selector: link',
  '    style:',
  '      curveStyle: bezier',
  '      lineColor: "#90a4ae"',
  '      lineWidth: 3',
  '      targetArrowShape: triangle',
  '      targetArrowColor: "#90a4ae"',
  '      labelColor: var(--topoviewer-fg-strong)',
  '      textBackgroundColor: var(--topoviewer-edge-label-bg)',
  '  - selector: path',
  '    style:',
  '      lineColor: "#ff9800"',
  '      lineWidth: 2',
  '      lineStyle: dashed',
  '      lineDashPattern: "10 6"',
  '      targetArrowShape: triangle',
  '      targetArrowColor: "#ff9800"',
  '  - selector: region',
  '    style:',
  '      backgroundColor: "rgba(25, 118, 210, 0.12)"',
  '      borderColor: "rgba(66, 165, 245, 0.58)"',
  '      borderWidth: 2',
  '      labelPosition: topCenter',
  '      labelMargin: 12',
  '      labelColor: var(--topoviewer-region-label-fg)',
  '      labelBackgroundColor: var(--topoviewer-region-label-bg)',
  ''
].join('\n');

export function starterAuthoringMapperText(sourceId = 'custom-topology') {
  return [
    'version: 1',
    'identity:',
    `  sourceId: ${sourceId}`,
    '  sourceIdLabel: source_id',
    'rules: []',
    ''
  ].join('\n');
}
