name: Docker Image CI V4

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: 
          actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
<<<<<<< HEAD:.github/workflows/docker-ci-v4.yml
          tag_name: "test"
          release_name: "test"
=======
          tag_name:  test
          release_name: Release test
>>>>>>> d14e5c344ebf83e4b4ac85b517d7e5ae5238600f:.github/workflows/main.yml
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
